Aymammet/sky

pyproject.toml
poetry pypeoject.toml file created
=> 01-poetry pypeoject.toml file created

.gitignore
=> SKY-4: Added gitignore

static/style.css, templates/footer.html
=> SKY-3: Footer.html design2

templates/register.html
Register design details uploaded. 
1. fontawesome been added
2. placeholders added
3. logo place size been adjusted with followed inputs
4. register button size increased
=> an/SKY-10: Register page design

README.md, templates/login.html
* login details upload and readme text updated
1.fontawesome added and placeholders
2.logo size adjusted with the rest
3.sign in button size increased
=> an/SKY-9: Login page design

templates/post-edit.html
1. Post added
2. Input for Changing title
3. label for find a file
=> an/SKY-5: Post-edit page design

.gitignore
database included into gittignore
=> an/SKY-19: Database added into gittignore

sky/settings.py, templates/base.html, templates/footer.html
*Container removed from class in footer
* Left description in footer shorter than was previously
=> an/SKY-63: Redesign footer template

profiles/views.py, templates/base.html, templates/profile-details.html
*Profile edit button hides when unauthorized user and Profile button on navbar too.
=> an/SKY-61: User Authentication

templates/profile-edit.html
*birth date row added in profile edit template
=> an/SKY-60: Birth Date Section on Profile Edit Template

sky/urls.py
path("" , include("posts.urls")  - removed from SKY url path
=> an/SKY-66: SKY URL Path Post Removed

templates/post-edit.html, templates/profile-details.html, templates/profile-edit.html
Javascript Elements Renamed in to  Profile-image and Post-image,  post-file and profile-file
=> an/SKY-62: Change Javascript ID Name in Post and Profile templates

profiles/views.py, templates/profile-edit.html
profile edit template form updated and gender section functions
=> an/SKY-64: Gender and Birth Date Model Function in Profile app

posts/views.py, sky/urls.py
=> an/SKY-66: SKY URL Path Post added back

profiles/views.py
*Only authorized users can edit its own page
=> an/SKY-50: Only Authorized User Edit Its Profile

posts/views.py
Post Edit View and Post Delete View updated with UserPassesTestMixin
=> an/SKY-68: Only Authorized User Edit & Delete Its Post

static/style.css, templates/post-delete.html, templates/post-edit.html
Delete button changed from bin to 'delete' written type.
wide size 
medium size
small size
=> an/SKY-69: Delete Button in Post-Edit HTML

main/views.py, posts/views.py, profiles/views.py, sky/urls.py, static/style.css, templates/404.html, templates/post-delete.html, templates/profile-details.html
*Design of 404.html page, update url and view
=> an/SKY-67: Design 404.html Page and Set it Up

posts/urls.py, posts/views.py, profiles/views.py, static/style.css, templates/404.html
Profile Edit View , Post Edit View and Post Delete View redirecting tot 404.hmtl
=> an/SKY-70: 404 Page is not Found

message/admin.py, message/urls.py, message/views.py, templates/rooms.html
Message field created and included content as message
=> an/SKY-34: Message with Javascript
